services:
  app:
    build: .
    container_name: system_b_registry
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      # Монтируем файл БД отдельно, чтобы он сохранялся между перезапусками
      # В .env DB_NAME должен указывать на /app/data/system_b.db для корректной работы
    restart: always

# Для SQLite мы используем локальный volume
volumes:
  sqlite_data:
